ruby "2.7.1"
source "https://rubygems.org"

gem "puma", "~> 5.4"
gem "quince", "~> 0.6"
# gem "quince", path: "../quince"
gem "method_source", "~> 1.0"
gem "rouge", "~> 3.26"
gem "svg-graph"
gem "rqrcode"
